import "./klondike/piles/pile.js";
import "./klondike/piles/remainderPile.js";
import "./klondike/piles/tableauPile.js";
import "./klondike/piles/foundationPile.js";
import "./klondike/scoring.js";
import "./klondike/klondike.js";
import "./klondike/board.js";
import "./klondike/game.js";
import "./cards/cards.js";